philschatz/octokat.js

src/grammar.coffee

This allows you get the details of an individual branch.

Add branch names to valid grammar

---

dist/octokat.js
src/chainer.coffee
src/replacer.coffee
test/all.coffee
test/object.spec.coffee

recursively check for OBJECT_MATCHER

---

src/replacer.coffee

Should fix #25 for multiple uploads with the same release object

replacer: use local variable for url

---

src/request.coffee

Fix binary bug.

---

src/replacer.coffee

Allows things like file.readBinary().
This is more for convenience than anything.

Chain anything with a url.

---

dist/octokat.js
src/replacer.coffee

Currently null date fields are being set to `Wed Dec 31 1969`. This changes them to be `null`

fix null dates

---

README.md
dist/octokat.js
src/octokat.coffee
test/simple.spec.coffee

for things like web hooks. Fixes #39

Add octo.parse() for parsing arbitrary JSON

---

.travis.yml
bower.json
package.json
test/index.html

* Test against nodejs v0.12 and iojs v3
* Update grunt-mocha-phantomjs (package.json), mocha (bower.json)
* Load mocha.js before coffee-script and es6-promise
*  Adjust mocha-phantomjs-core (1.0.0)

Test against nodejs v0.12 and iojs v3

---

dist/octokat.js
src/replacer.coffee

use `for i in Object.keys(obj)` instead of naively using `for i, val of obj`
Fixes #55

use Object.keys instead

---

src/grammar.coffee
test/simple.spec.coffee

Fixes #56 
Fixtures added in https://github.com/philschatz/octokat.js-fixtures/issues/1

Added support for refs.tags

---

.travis.yml

* Test against nodejs v4
* Remove unnecessary target
* iojs
* comment outed v0.8

Test against nodejs v4

---

dist/octokat.js
src/request.coffee

There was a variable that was undefined (oops!). This fixes #87

Fixes Getting reference error on fetch if there is no response

---

src/grammar.coffee

See https://developer.github.com/v3/repos/hooks/#ping-a-hook

hooks can be pinged via `POST .../hooks/:id/pings`

---

dist/octokat.js
src/request.coffee

The default cache handler was being reset, effectively nullifying caching. This adds it back!
fixes #92

fix the default cacheHandler

---

src/base.js

Every requests are crashing on philschatz/gh-board because of that.
Fix https://github.com/philschatz/gh-board/issues/63.

fix accessing null options

---

src/grammar/tree-options.js
src/grammar/url-validator.coffee

https://developer.github.com/v3/repos/#list-all-public-repositories

Adds support for public repositories

---

src/grammar/tree-options.js
src/grammar/url-validator.coffee

This adds the [Collaborator Permissions API](https://developer.github.com/changes/2017-03-29-official-org-membership/)

adds collaborator permission API

---

src/requester.js

:wave:
This lets consumers provide a custom user agent for requests.
Let me know if I need to test or document this anywhere!

Accept a user agent

---

README.md

document usage in desktop/desktop

---

dist/octokat.js
src/adapters/fetch-browser.js

Call window.fetch properly
