.gitignore, .npmignore, Gruntfile.coffee, bower.json, dist/octokat.js, index.js, package.json
This should fix #10 instead of having a postinstall hook that relies on `coffee` as in #19
=> Build JS files so browserify works

src/request.coffee
The client options accept header is currently ignored.
=> Fix overriding of the request header.

README.md, src/grammar.coffee, src/request.coffee
sends the preview API header when the route is called
Adds support for:
- Licenses
- OAuth Authorizations
- `starred_at`
=> add preview apis (license, star, authorizations)

dist/octokat.js, src/replacer.coffee, test/simple.spec.coffee
fixes #42 . Things like the following are now allowed:
```coffee
client.users('philschatz').fetch()
.then (user) ->
console.log(user.avatarUrl)
```
=> provide fooUrl for non-templated url fields

src/grammar.coffee
Currently the grammar allows comparing 2 commits but gives a warning when trying to compare a branch/tag.
=> support comparing tags and branches instead of just sha

dist/octokat.js, src/request.coffee
The event that is fired on every request includes some but not all the rate limit headers. This adds the remaining one, `reset` (When the API's rate limit will reset).
Currently, an additional request to `/rate_limit` is required to get that information.
TODO:
=> include the reset time in rate limit data

README.md, dist/octokat.js, src/octokat.coffee, test/simple.spec.coffee, test/test-config.coffee
This adds an additional config option: `octo = new Octokat({disableHypermedia: true})`
Normally the response from GitHub is modified to do the following:
- convert underscore_values to camelCase
- convert strings to `Date` objects
- convert hypermedia `*_url` to methods that can be called
Sometimes the additional processing is overkill and just a simple JSON response is all that is needed.
=> add option to disable modifying the API response JSON

Gruntfile.coffee, dist/octokat.js, src/chainer.coffee, src/helper-querystring.coffee, src/replacer.coffee, test/node.coffee, test/replacer.spec.coffee
fixes #72. The `upload_url` pattern changed and an additional optional argument was added which broke the pattern matcher. This fixes the immediate problem of not being able to upload resources. This solution should (hopefully) work for GitHub Enterprise 2.3 and 2.4
TODO:
=> Fix resource upload url pattern

Gruntfile.coffee, README.md, dist/octokat.js, src/chainer.coffee, src/helper-promise.coffee, src/octokat.coffee, src/verb-methods.coffee, test/simple.spec.coffee
fixes #76
Add support for supporting URLs directly instead of using Octokat to construct them.
You can still use Octokat for sending authentication information, caching, pagination,
and parsing Hypermedia.
```js
// Specify the entire URL
octo.fromUrl("https://api.github.com/repos/philschatz/octokat.js/issues/1").fetch(cb);
// Or, just the path
octo.fromUrl("/repos/philschatz/octokat.js/issues").fetch({state: 'open'}, cb);
```
=> add support for using a URL directly

README.md, example-tonic.js, package.json
Adds a link at the top of `README.md` to _Try Before You Buy_<sup>TM</sup> with simple example code that lists all the open issues for a repository.
Once a new version is published to `npm` the example should load up at https://tonicdev.com/npm/octokat
=> add REPL example using tonicdev

src/grammar.coffee
In both cases it's allowed to use the name of a branch:
- `curl -s https://api.github.com/repos/michaelcontento/circleci-matrix/statuses/master`
- `curl -s https://api.github.com/repos/michaelcontento/circleci-matrix/commits/master`
- `curl -s https://api.github.com/repos/michaelcontento/circleci-matrix/commits/master/status`
=> Fix gammar for /repos/:org/:name/(commits|statuses)/:ref

dist/octokat.js, src/request.coffee
octokat failed today on my machine because GitHub returned a 304 status code when the cache was empty. I think that sending an "If-Modified-Since" header is wrong when we don't expect a 304 response status. Removing the "If-Modified-Since" header in the request fixed my issue, that's why I am opening this pull request
Here is a js file with which you can reproduce the issue on node.js (after making sure the `co` and `octokat` npm packages are installed):
```js
"use strict";
const co = require("co");
const Octokat = require("octokat");
co(function * () {
const octokat = new Octokat({
// note that I used a token here because my ip was otherwise rate-limited 
});
const response = yield octokat.repos("ariatemplates", "ariatemplates").commits.fetch({
sha: "master"
});
console.log(response); …
```
=> Removing the "If-Modified-Since" request header when the cache is empty (as it causes issues)

package.json, webpack.config-browser.js, webpack.config-browsertests.js
Webpack 2.3 began requiring absolute paths for the output directory. This addresses that change.
=> update webpack to 2.3.1

src/plugins/cache-handler.js
Trying to hunt down a rare error with how we're using Octokat - starting with what method triggered this...
=> make cacheHandler error easier to trace

README.md
It took me a minute to realise I could use the Github API's per_page parameter in fetch(), so proposing to document it for others.
=> Mention per_page parameter in README.md

src/grammar/object-matcher.coffee, src/grammar/tree-options.js, src/grammar/url-validator.coffee
Adds support for URLs that use the repository ID (instead of the username and repo name). Examples:
- https://api.github.com/repositories/20044005
- https://api.github.com/repositories/20044005/pulls
- https://api.github.com/repositories/20044005/stargazers
fixes #150.
=> add /repositories/### URL structure

src/requester.js, test/emitter.spec.js
When there is an `end` event, it was being emitted with the current global `eventId` and not the ID that the request started with. This would result in `end` events with the same (and incorrect) ID when there are concurrent requests.
This makes sure to save the request's own ID after incrementing the global, and adds a test.
=> Fix end event IDs when there are concurrent requests

src/grammar/preview-headers.coffee, src/grammar/tree-options.js, src/grammar/url-validator.coffee
This adds support for the [Projects API](https://developer.github.com/v3/projects/) and fixes #144
Example (you must choose a repository that has the Projects enabled and you must be logged in):
```js
var Octo = require('./')
var octo = new Octo({token: process.env['GH_TOKEN']})
octo.repos('philschatz', 'gh-demo').projects.fetch()
.then((res) => {
// console.log(res)
return res.items[0].columns.fetch()
.then((cols) => {
// console.log(cols)
return cols.items[0].cards.fetch()
.then((cards) => {
// console.log(cards)
return cards.items[0].fetch()
.then((card) => {
console.log(card)
})
})
})
})
```
=> add routes for the Projects API

examples/README.md, src/grammar/tree-options.js, src/grammar/url-validator.coffee
This API was recently added: https://developer.github.com/v3/users/emails/#list-public-email-addresses-for-a-user
I used #155 as a reference to figure out how to add this - not sure if I've missed anything, or if you would like some extra test coverage.
=> add support for /user/public_emails

src/grammar/url-validator.coffee
This is a nondocumented public way of getting a repository by ID.
=> Adding repositories/id to URL_VALIDATOR

README.md
After having a friend try to install this and getting stuck, I realize that there is no install section. Having it at the top makes running this a bit easier - otherwise, you have to search for install to learn the name of the repo. This should help onboarding new users, with minimal amount of space.
=> Adding Install in its own section

dist/octokat.js, src/requester.js
Looking to get an issue around inappropriate `JSON.parse` usage, as we've seen some rare errors from the GitHub API that are returning HTML instead of JSON - see https://github.com/desktop/desktop/issues/1505
I had [some notes](https://github.com/desktop/desktop/issues/1505#issuecomment-303974765) on how we should be more defensive by inspecting the header of the response. The new `fetch` API has a similar issue, so we should check here as well.
Here's a demo:
=> Is it Really JSON Though?

src/plugins/fetch-all.js
I was trying to use the `fetchAll` plugin and it crashed with the following error
> Octokat Error: Calling fetchAll on a request that does not yield an array
I traced it down to the `fetchNextPage` function calling the requester with `undefined` instead of a URL and found this little typo. Worth noting is that this was in the [desktop/desktop](https://github.com/desktop/desktop) repo where we don't use the `camelCase` plugin. I suspect this might have worked just fine had we used the `camelCase` plugin.
=> Fix fetchAll typo

package.json, test/browser.js, test/node.js, test/ruby-specs/commit-comments.spec.js, test/ruby-specs/contents.spec.js, test/ruby-specs/gists.spec.js, test/simple.spec.js
When converting from Coffeescript to JavaScript for the tests (and updating mocha) failing when an Array is not returned was missed.
=> fix tests that validate an Array is returned

README.md
https://github.com/desktop/desktop/blob/9d5aa6f7f41c3ed6902e5759f41877084fbef65e/app/package.json#L19
=> octokat.js no longer used by latest GitHub Desktop

src/grammar/url-validator.coffee
ref #202  (link header returns urls with /organizations/12345/repos?page=2 and similar)
Organizations url require an numeric id
https://api.github.com/organizations/1089146
Does not work:
https://api.github.com/organizations/atom
vs 
https://api.github.com/orgs/atom
The new regexp matches should match all of the following (and more):
- https://api.github.com/organizations
- https://api.github.com/orgs/atom
- https://api.github.com/organizations/1089146
- https://api.github.com/organizations/1089146/repos
etc
=> Added support for organizations urls
